Add underline to active page in navbar
virtrolio/virtrolio-site pull request #381
Opened 2021-05-26 23:21 UTC by ricetech

Closes virtrolio/issue-tracking#20

2021-05-27 23:48 UTC, jonapap submitted a review, later dismissed

2021-05-28 22:53 UTC, janakitti commented on src/app/core/navbar/navbar.component.css
> +  text-underline-offset: 2px;
Could we maybe make this offset a bit greater (0.2em seems to look nice)

2021-05-28 22:53 UTC, janakitti requested changes
Underline offset

2021-05-29 01:04 UTC, janakitti approved these changes

2021-05-29 04:36 UTC, jonapap approved these changes

2021-05-29 06:09 UTC, merged