Merge Ng-For-Static-Pages into beta-main
virtrolio/virtrolio-site pull request #71
Opened 2020-07-11 20:51 UTC by GuyInFridge

- Convert About and FAQ pages to use .json's and *ngFor's to clean up the HTML code

2020-07-11 23:58 UTC, ricetech requested changes
You are incorrectly displaying properties that don't exist (websites/instagrams for people that don't have them)

2020-07-12 13:21 UTC, GuyInFridge commented
@ricetech I thought we wanted that for consistency? Or at least having all the social links in the same order. I remember we mentioned doing it that way before but I just ended up only putting the ones that were there. @janakitti @TommyHuang-dev what do you guys think?

2020-07-12 13:23 UTC, GuyInFridge commented
@TommyHuang-dev has agreed with you, @ricetech. I will make the changes.

2020-07-12 14:01 UTC, janakitti commented
Yeah I guess I agree with @ricetech too since it doesn't make sense to have links to nowhere. You can just have an ngIf inside the ngFor to check if a field is nonexistent.

2020-07-12 20:04 UTC, ricetech commented
> @ricetech I thought we wanted that for consistency? Or at least having all the social links in the same order. I remember we mentioned doing it that way before but I just ended up only putting the ones that were there. @janakitti @TommyHuang-dev what do you guys think?
> 
> Not hard to change, just an `*ngIf`.

They should be in the same order for consistency, yes, but that doesn't involve showing fields that don't exist - it just makes it look like we forgot to ask the person for their social media handles.

2020-07-12 22:18 UTC, janakitti approved these changes

2020-07-12 22:18 UTC, janakitti commented on src/app/pages/about/about.component.html
> +            <li *ngIf="contributor.social.github">Github:
```suggestion
            <li *ngIf="contributor.social.github">GitHub:
```

2020-07-12 23:52 UTC, LillianHuang-dev approved these changes

2020-07-14 01:28 UTC, ricetech requested changes

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/about/about.component.html
> +          <img alt="Silly picture of {{contributor.name}}" class="img-fluid silly-picture" src="{{ contributor.images.silly }}">
You can't add spaces in one tag and leave them out in the next xD
```suggestion
          <img alt="Picture of {{ contributor.name }}" class="img-fluid regular-picture" src="{{ contributor.images.regular }}">
          <img alt="Silly picture of {{ contributor.name }}" class="img-fluid silly-picture" src="{{ contributor.images.silly }}">
```

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/about/about.component.html
> +            <a href="{{contributor.sharingLink}}" target="_blank">Click here to sign {{contributor.name}}'s virtrolio.</a>
spaces
```suggestion
            <a href="{{ contributor.sharingLink }}" target="_blank">Click here to sign {{ contributor.name }}'s virtrolio.</a>
```

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/about/about.component.html
> +              <a href="https://{{contributor.social.website}}" target="_blank">{{contributor.social.website}}</a>
```suggestion
          <p><strong>Contact {{ contributor.name }}</strong></p>
          <ul>
            <li *ngIf="contributor.social.github">GitHub:
              <a href="https://github.com/{{ contributor.social.github }}"
                 target="_blank">{{ contributor.social.github }}</a>
            </li>
            <li *ngIf="contributor.social.instagram">Instagram:
              <a href="https://www.instagram.com/{{ contributor.social.instagram }}"
                 target="_blank" *ngIf="contributor.social.instagram">@{{ contributor.social.instagram }}</a>
            </li>
            <li *ngIf="contributor.social.linkedIn">LinkedIn:
              <a href="{{ contributor.social.linkedIn }}" target="_blank">{{ contributor.name }}</a>
            </li>
            <li *ngIf="contributor.social.website">Website:
              <a href="https://{{ contributor.social.website }}" target="_blank">{{ contributor.social.website }}</a>
```

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/faq/faq.component.html
> +    <h2>{{section.sectionTitle}}</h2>
```suggestion
    <h2>{{ section.sectionTitle }}</h2>
```

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/faq/faq.component.html
> +      <div class="card-header" id="question{{s}}-{{q}}">
```suggestion
      <div class="card-header" id="question{{ s }}-{{ q }}">
```

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/faq/faq.component.html
> +            {{question.question}}
```suggestion
            {{ question.question }}
```

2020-07-14 01:28 UTC, ricetech commented on src/app/pages/faq/faq.component.html
> +      <div aria-labelledby="question" class="collapse" [attr.data-parent]="'#section-header'+s" id="answer{{s}}-{{q}}">
```suggestion
      <div aria-labelledby="question" class="collapse" [attr.data-parent]="'#section-header'+s" id="answer{{ s }}-{{ q }}">
```

2020-07-14 17:51 UTC, ricetech approved these changes

2020-07-14 17:51 UTC, merged