Update README to include table of libraries used
virtrolio/virtrolio-site pull request #77
Opened 2020-07-19 02:35 UTC by TommyHuang-dev

* Add table of libraries used
* Add a short message stating that anyone can contribute through a PR

2020-07-20 02:49 UTC, ricetech requested changes
Couldn't you use hyperlinks in the library name to avoid having a separate link column like doing [this](https://bit.ly/virtrolioYouT00b)?

2020-07-20 16:28 UTC, DabeerAzeez requested changes

2020-07-20 16:28 UTC, GuyInFridge commented on README.md
> +Virtrolio is built using Angular and Bootstrap in the front end, with Firebase for data storage, hosting, and user authentication. Firebase was chosen for its ease of use and integration of various s
```suggestion
Virtrolio is built using Angular and Bootstrap in the front end, with Firebase for data storage, hosting, and user authentication. Firebase was chosen for its ease of use and integration of various secure login authentication providers. If you would like to help us further improve Virtrolio, feel free to fork our repository and create a pull request.
```

2020-07-20 16:29 UTC, GuyInFridge commented
> Couldn't you use hyperlinks in the library name to avoid having a separate link column like doing [this](https://bit.ly/virtrolioYouT00b)?

Meh. I think it looks nice the way it's set up.

2020-07-23 01:11 UTC, ricetech approved these changes

2020-07-25 14:31 UTC, DabeerAzeez approved these changes

2020-07-25 14:40 UTC, merged